using GridCreator.Commands;
using GridCreator.Model;
using GridCreator.View.Pages;
using System.Windows;
using System.Windows.Input;

namespace GridCreator.ViewModel
{
    class ChangePageViewModel
    {
        public ICommand GoToNextPageCommand { get; set; }
        public ICommand GoToPreviousPageCommand { get; set; }
        public ICommand InsertAutoGeneratedCodeCommand { get; set; }
        public ICommand SetAddColumnOptionCommand { get; set; }

        private JqGridModel jqGridModel;
        private Window BaseWindow { get; }

        public ChangePageViewModel()
        {
            GoToNextPageCommand = new CustomCommand(GoToNextPage, CanGoToNextPage);
            InsertAutoGeneratedCodeCommand = new CustomCommand(InsertAutoGeneratedCode, CanInsertAutoGeneratedCode);
            GoToPreviousPageCommand = new CustomCommand(GoToPreviousPage, CanGoToPreviousPage);
            SetAddColumnOptionCommand = new CustomCommand(SetAddColumnOption, CanSetAddColumnOption);

            jqGridModel = JqGridModelSingletonFactory.Instance;
        }

        public bool CanGoToNextPage(object parameter)
        {
            return true;
        }

        public void GoToNextPage(object parameter)
        {
            var baseWindowInstance = ShowWizardForGridCreation.BaseWindowInstance;
            var currentPage = baseWindowInstance.testFrame.Content.GetType().Name;

            if (currentPage == PageNames.ChoseDataSourcePage)
            {
                switch (jqGridModel.AddColumnsOption)
                {
                    case "Manualy add columns and their definition":
                    baseWindowInstance.testFrame.NavigationService.Navigate(new Page1());
                        break;

                    case "Add columns from SQL Server":
                        baseWindowInstance.testFrame.NavigationService.Navigate(new Page2());
                        break;
                }
            }

        }
        //
        public bool CanGoToPreviousPage(object parameter)
        {
            return true;
        }

        public void GoToPreviousPage(object parameter)
        {
            var baseWindowInstance = ShowWizardForGridCreation.BaseWindowInstance;
            var currentPage = baseWindowInstance.testFrame.Content.GetType().Name;

            if (currentPage == PageNames.Page1)
                baseWindowInstance.testFrame.NavigationService.Navigate(new ChoseDataSourcePage());
        }
        //

        public bool CanInsertAutoGeneratedCode(object parameter)
        {
            return true;
        }

        public void InsertAutoGeneratedCode(object parameter)
        {
            var ShowWizardForGridCreationInstance = ShowWizardForGridCreation.Instance;
            ShowWizardForGridCreationInstance.test();
        }
        //
        public bool CanSetAddColumnOption(object parameter)
        {
            return true;
        }

        public void SetAddColumnOption(object parameter)
        {
            jqGridModel.AddColumnsOption = parameter.ToString();
        }
    }
}
